# Generated by Django 2.2.5 on 2020-02-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('idgenr_general', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=50, verbose_name='Placa')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': ('Lista',),
                'verbose_name_plural': ('Listas',),
                'db_table': 'General',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('cedula', models.CharField(max_length=45)),
                ('placa_carro', models.CharField(max_length=50)),
                ('descripcion_problema', models.TextField(max_length=200)),
                ('imagen', models.ImageField(max_length=50, upload_to='')),
                ('id_genr_estado', models.ForeignKey(db_column='id_genr_estado', on_delete=django.db.models.deletion.CASCADE, related_name='fk_usuario_estado', to='inventario.General')),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuarios',),
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(max_length=50, upload_to='')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='inventario.Usuario')),
            ],
            options={
                'verbose_name': ('producto del usuario',),
                'verbose_name_plural': ('productos del usuarios',),
                'db_table': 'Productos',
            },
        ),
    ]
